AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3.3
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
